### ISSUE TITLE
Add  image upload in Form

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#16]
## Value Proposition
As a Hoster[^1], I want to be able to add pictures of my studio to my listings so that general Users of the Web App are able to compare studios depending on how they look.
## Description
The Form already exists and uploads all existing  Form inputs to MongoDB to then display the Information in listing it in form of a card in the search results page. Here we will add the Image Upload Input and integrate it in the existing form and form submit handler.
In addtion there is also already a User Sign in to link the Database entries and studio listings to a specific User Id

Below are all the necessary inputs for completing this issue

-Image Upload

![Screenshot 2022-10-19 at 10 04 48](https://user-images.githubusercontent.com/68496958/196632983-663c99a7-df85-40e5-9ae2-34dc0486d337.png)

## Acception Criteria 
- [x] Image File Upload Input:
styled Input to select Image Files for upload. Only accept's Image files and max. 1MB
- [x] Cloudinary middleman setup:
Cloudinary will take care of image storage and its optimisation. It'll be signed uploads which requires the user to be authenticated. This way only signed up Users can upload an image.
- [x] Save Image to listing property in MongoDB:
The returned Image URL from Cloudinary will be attached to the formData before it gets send to MongoDB

- ## Tasks
- [x] create file upload input with basic styling
- [x] create a state to store that file till form submit
- [x] create description for "good studio pictures"
- [x] setup of Cloudinary: - signed Image uploads configuration in Cloudinary 
- [x] Create Image-Upload handler: - fires on Submit - awaits Image URL as return
- [x] Integrate Image-Upload handler in Submit handler: -attach url to formData

[^1]: Type of User who wants to list their music studio

**Comment by F-Kirchhoff** [comment]
Hey Ozan, can you add some more detail about the acceptance criteria and Tasks? make sure you describe in detail the expected behavior and all steps required to upload the image.

**Comment by F-Kirchhoff** [comment]
Ah no, I didn't mean to write details about the tasks, I wanted so see more steps and tasks. The goal is to write the tasks such that you don't have to think about how to solve a problem when you start coding.
