### ISSUE TITLE
create Form for creating studio listing

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#7]
## Value Proposition
As a Hoster[^1], I want to be able to create a studio listing so that general Users of the Web App are able to compare my services with those from other Hoster listings.
## Description
Below are all the necessary inputs to be able to fit the Dummy Data used in #4 . For this Userstory only the main focused inputs will be worked on. This includes the 

- Title
- Studiotype
- Opening hours
- Services
- Soundengineer
- Studio pricing
- location features

![Screenshot 2022-10-19 at 10 04 35](https://user-images.githubusercontent.com/68496958/196632938-a1942ff4-4783-497b-9e5f-8fc48a2fe4ab.png)
![Screenshot 2022-10-19 at 10 04 58](https://user-images.githubusercontent.com/68496958/196633016-8e171490-fcb0-46d1-9c01-4edbf7ed288e.png)
![Screenshot 2022-10-19 at 10 05 06](https://user-images.githubusercontent.com/68496958/196633039-e62925b1-f89d-4c7c-be35-8fd851ab51d5.png)
![Screenshot 2022-10-19 at 10 05 17](https://user-images.githubusercontent.com/68496958/196633078-863b6857-6a8f-4dd1-9d96-9ccdb44bf08e.png)
![Screenshot 2022-10-19 at 10 05 32](https://user-images.githubusercontent.com/68496958/196633146-436cf903-ad62-40ba-a3fe-2f87b4bc131a.png)

## Acception Criteria 
- [x] Title, studio type, services, sound engineer, pricing and location features input's work and are functional

- ## Tasks
- Add following inputs (including: labels, aria, names)
- [x] Create Title input (Text)
- [x] Create Mediafile Upload (File)
- [x] Create Opening Hours (Radio)
- [x] Create Studiotype input (Buttons)
- [x] Create location features input (Checkbox)
- [x] Create Services input (Checkboxes)
- [x] Create Soundengineer input (Radio)
- [x] Create Studio pricing input (Text)
- [x] add states handler for all inputs

[^1]: Type of User who wants to list their music studio

**Comment by F-Kirchhoff** [comment]
Hey Ozan, this user story is too big. please split the input form into multiple user storys. First, only the main features should be covered by the inputs, from there on build up your form with more user stories. 

Secondly, you have to state every single input field and button in the acceptance criteria and tasks. Make sure you don't forget any. Please be precise which options the user should be able to take.

Finally, you can remove the next two user stories, even your first input Form should be working correctly, only that it creates a "rough" data sheet of the studio.

I hope that helped!

**Comment by CathrinTruchan** [comment]
Hi Ozan, maybe you could describe what type of inputs you want to use for the different input fields e.g. text, radio, dropdown etc? 
And a more detailed description of the task "add states" would be nice :)
